Add README
genophenoenvo/terraref-datasets pull request #119
Opened 2020-11-03 15:44 UTC by MagicMilly

Still need

- links to output data on CyVerse 
    - could probably also upload to repo in `data` > `processed` due to being small files
- to update trait data cleaning notebooks within repo and on CyVerse

2020-11-09 19:45 UTC, dlebauer requested changes
There are a number of details to discuss ... lets follow up with a real-time review and revision

2020-11-09 19:45 UTC, dlebauer commented on README.md
> +TERRA-REF data and other documents are licensed under CC-By. All software is licensed under MIT.
data from Season 4 and 6 contained in this repository are licensed under CC-0.

2020-11-09 19:45 UTC, dlebauer commented on README.md
> +Please contact these individuals with any questions
Remove Todd and Nadia's name from this derivative dataset that they are not familiar with. 

Also, add an empty line below the heading `### Contacts`

2020-11-09 19:45 UTC, dlebauer commented on README.md
> +---
Data from KSU are unpublished.

Data from Clemson come from a separate citation that should be listed here

2020-11-09 19:45 UTC, dlebauer commented on README.md
> +TERRA-REF data and other documents are licensed under CC-By. All software is licensed under MIT.
I think "Licenses" Contacts and Citations can be combined under a header "Data Use" this section can be combined with

2020-11-20 17:04 UTC, dlebauer commented
TODO: 

- [ ] update links to updated csvs on CyVerse that have fewer columns and match what is on dryad
- [ ] update trait data description  
- [ ] update weather data to match how trait data is presented
- [ ] update the proj. org. 
  - point to where all data is org. on CyVerse
  - put anything small enough (notebooks, references, scripts) in github

2020-12-21 21:23 UTC, MagicMilly commented
All notebooks, raw downloads, weather script, and derived datasets are on CyVerse in the GenoPhenoEnvo data folder. The notebooks are in Pull Request #122. The task to `update weather data to match how trait data is presented` may need clarification from David. Tag me in a comment if there are any questions or permission issues. There are some outdated notebooks on CyVerse that Tyson has permission to delete.

2020-12-23 21:40 UTC, merged