Added instructions for using CyVerse VICE apps
genophenoenvo/terraref-datasets pull request #50
Opened 2020-04-08 17:08 UTC by MagicMilly

2020-04-09 16:38 UTC, dlebauer requested changes
* The README should start with additional information about the purpose of this repository, and then have a section on "cleaning data using vice" or such
* it might help to add screenshots?
* I think @tyson-swetnam can cache the image so it doesn't take as long to load

2020-04-24 17:08 UTC, dlebauer commented on README.md
> +
```suggestion

## Genomics data

https://datacommons.cyverse.org/browse/iplant/home/shared/terraref/genomics/derived_data/bap/resequencing/danforth_center/version1/hapmap

```

2020-04-24 17:12 UTC, dlebauer commented
Maybe some of this info should go in the documentation repository (perhaps as a separate md) or at least link to this readme from the documentation readme https://github.com/genophenoenvo/documentation/blob/master/README.md

2020-07-16 15:28 UTC, MagicMilly commented
Closing this PR because we've moved away from using the CyVerse app, so it is no longer updated, and even with instructions was difficult for collaborators to use.

2020-07-16 15:28 UTC, closed without merging